In [1]:
import pandas as pd
import numpy as np
import re
import datetime
from dateutil.relativedelta import relativedelta
from datetime import date
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
%matplotlib inline

In [2]:
file1 = r"C:\Users\Mr. Jarvis\Desktop\python project\project 2\carvan_train.csv"

In [3]:
file2 = r"C:\Users\Mr. Jarvis\Desktop\python project\project 2\carvan_test.csv"

In [4]:
bd_train = pd.read_csv(file1)

In [5]:
bd_test = pd.read_csv(file2)

In [6]:
bd_train.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  ...  V77  V78  V79  V80  V81  V82  \
0  33   1   3   2   8   0   5   1   3    7  ...    0    0    0    1    0    0   
1  37   1   2   2   8   1   4   1   4    6  ...    0    0    0    1    0    0   
2  37   1   2   2   8   0   4   2   4    3  ...    0    0    0    1    0    0   
3   9   1   3   3   3   2   3   2   4    5  ...    0    0    0    1    0    0   
4  40   1   4   2  10   1   4   1   4    7  ...    0    0    0    1    0    0   

   V83  V84  V85  V86  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  

[5 rows x 86 columns]

In [7]:
bd_test.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  ...  V76  V77  V78  V79  V80  V81  \
0  33   1   4   2   8   0   6   0   3    5  ...    0    0    0    0    1    0   
1   6   1   3   2   2   0   5   0   4    5  ...    2    0    0    0    1    0   
2  39   1   3   3   9   1   4   2   3    5  ...    1    0    0    0    1    0   
3   9   1   2   3   3   2   3   2   4    5  ...    0    0    0    0    1    0   
4  31   1   2   4   7   0   2   0   7    9  ...    0    0    0    0    1    0   

   V82  V83  V84  V85  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0  

[5 rows x 85 columns]

In [8]:
pd.set_option('display.max_columns',500)
pd.set_option('display.max_rows',500)

In [9]:
bd_test.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16  V17  \
0  33   1   4   2   8   0   6   0   3    5    0    4    1    1    8    2    2   
1   6   1   3   2   2   0   5   0   4    5    2    2    1    4    5    5    4   
2  39   1   3   3   9   1   4   2   3    5    2    3    2    3    6    2    4   
3   9   1   2   3   3   2   3   2   4    5    4    1    2    4    4    2    4   
4  31   1   2   4   7   0   2   0   7    9    0    0    0    6    3    0    0   

   V18  V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  V31  V32  \
0    6    0    0    1    2    6    1    0    2    1    5    3    1    8    8   
1    0    5    0    0    4    0    0    4    3    0    2    1    3    6    9   
2    4    2    1    1    3    2    2    1    1    5    2    1    1    8    6   
3    4    2    1    1    5    1    2    3    1    3    2    2    3    6    7   
4    9    0    0    0    2    4    4    0    0    0    7    2    9    0    7   

   V33  V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  V45  V46  V47  \
0    1    1    8    1    3    3    3    0    0    3    3    1    0    0    0   
1    0    0    7    2    1    1    5    4    0    6    8    2    0    0    6   
2    2    2    6    3    2    4    3    1    0    3    5    2    0    0    6   
3    2    1    7    2    2    5    3    1    0    4    4    2    0    0    5   
4    2    0    9    0    5    4    0    0    0    3    1    2    0    0    0   

   V48  V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  V59  V60  V61  V62  \
0    0    0    0    0    0    0    0    0    0    0    0    4    0    0    0   
1    0    4    0    0    0    0    0    3    0    0    0    4    0    0    0   
2    0    0    0    0    0    0    0    4    0    0    0    4    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    3    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0   

   V63  V64  V65  V66  V67  V68  V69  V70  V71  V72  V73  V74  V75  V76  V77  \
0    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0   
1    0    0    1    0    0    1    0    1    0    0    0    0    0    2    0   
2    0    0    1    0    0    1    0    0    0    0    0    0    0    1    0   
3    0    0    1    0    0    1    0    0    0    0    0    0    0    0    0   
4    0    0    1    0    0    0    0    0    0    0    0    0    0    0    0   

   V78  V79  V80  V81  V82  V83  V84  V85  
0    0    0    1    0    0    0    0    0  
1    0    0    1    0    0    0    0    0  
2    0    0    1    0    0    0    0    0  
3    0    0    1    0    0    0    0    0  
4    0    0    1    0    0    0    0    0

In [10]:
bd_train.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
V6     0
V7     0
V8     0
V9     0
V10    0
V11    0
V12    0
V13    0
V14    0
V15    0
V16    0
V17    0
V18    0
V19    0
V20    0
V21    0
V22    0
V23    0
V24    0
V25    0
V26    0
V27    0
V28    0
V29    0
V30    0
V31    0
V32    0
V33    0
V34    0
V35    0
V36    0
V37    0
V38    0
V39    0
V40    0
V41    0
V42    0
V43    0
V44    0
V45    0
V46    0
V47    0
V48    0
V49    0
V50    0
V51    0
V52    0
V53    0
V54    0
V55    0
V56    0
V57    0
V58    0
V59    0
V60    0
V61    0
V62    0
V63    0
V64    0
V65    0
V66    0
V67    0
V68    0
V69    0
V70    0
V71    0
V72    0
V73    0
V74    0
V75    0
V76    0
V77    0
V78    0
V79    0
V80    0
V81    0
V82    0
V83    0
V84    0
V85    0
V86    0
dtype: int64

In [11]:
bd_test.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
V6     0
V7     0
V8     0
V9     0
V10    0
V11    0
V12    0
V13    0
V14    0
V15    0
V16    0
V17    0
V18    0
V19    0
V20    0
V21    0
V22    0
V23    0
V24    0
V25    0
V26    0
V27    0
V28    0
V29    0
V30    0
V31    0
V32    0
V33    0
V34    0
V35    0
V36    0
V37    0
V38    0
V39    0
V40    0
V41    0
V42    0
V43    0
V44    0
V45    0
V46    0
V47    0
V48    0
V49    0
V50    0
V51    0
V52    0
V53    0
V54    0
V55    0
V56    0
V57    0
V58    0
V59    0
V60    0
V61    0
V62    0
V63    0
V64    0
V65    0
V66    0
V67    0
V68    0
V69    0
V70    0
V71    0
V72    0
V73    0
V74    0
V75    0
V76    0
V77    0
V78    0
V79    0
V80    0
V81    0
V82    0
V83    0
V84    0
V85    0
dtype: int64

In [12]:
bd_train.shape

(5822, 86)

In [13]:
bd_test.shape

(4000, 85)

In [14]:
bd_train['V1']

0       33
1       37
2       37
3        9
4       40
        ..
5817    36
5818    35
5819    33
5820    34
5821    33
Name: V1, Length: 5822, dtype: int64

In [15]:
bd_train.shape

(5822, 86)

In [16]:
bd_test.shape

(4000, 85)

In [17]:
bd_train.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85', 'V86'],
      dtype='object')

In [18]:
bd_test.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85'],
      dtype='object')

In [19]:
bd_test['V86']=np.nan

In [20]:
bd_train['data'] = 'train'
bd_test['data'] = 'test'
bd_test=bd_test[bd_train.columns] # the columns in the two data frames should
#be in the same order to enable concatenation
bd_all=pd.concat([bd_train,bd_test],axis=0)

In [21]:
bd_all.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16  V17  \
0  33   1   3   2   8   0   5   1   3    7    0    2    1    2    6    1    2   
1  37   1   2   2   8   1   4   1   4    6    2    2    0    4    5    0    5   
2  37   1   2   2   8   0   4   2   4    3    2    4    4    4    2    0    5   
3   9   1   3   3   3   2   3   2   4    5    2    2    2    3    4    3    4   
4  40   1   4   2  10   1   4   1   4    7    1    2    2    4    4    5    4   

   V18  V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  V31  V32  \
0    7    1    0    1    2    5    2    1    1    2    6    1    1    8    8   
1    4    0    0    0    5    0    4    0    2    3    5    0    2    7    7   
2    4    0    0    0    7    0    2    0    5    0    4    0    7    2    7   
3    2    4    0    0    3    1    2    3    2    1    4    0    5    4    9   
4    0    0    5    4    0    0    0    9    0    0    0    0    4    5    6   

   V33  V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  V45  V46  V47  \
0    0    1    8    1    0    4    5    0    0    4    3    0    0    0    6   
1    1    2    6    3    2    0    5    2    0    5    4    2    0    0    0   
2    0    2    9    0    4    5    0    0    0    3    4    2    0    0    6   
3    0    0    7    2    1    5    3    0    0    4    4    0    0    0    6   
4    2    1    5    4    0    0    9    0    0    6    3    0    0    0    0   

   V48  V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  V59  V60  V61  V62  \
0    0    0    0    0    0    0    0    0    0    0    0    5    0    0    0   
1    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    6    0    0    0   

   V63  V64  V65  V66  V67  V68  V69  V70  V71  V72  V73  V74  V75  V76  V77  \
0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   
1    0    0    2    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    1    0    0    1    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

   V78  V79  V80  V81  V82  V83  V84  V85  V86   data  
0    0    0    1    0    0    0    0    0  0.0  train  
1    0    0    1    0    0    0    0    0  0.0  train  
2    0    0    1    0    0    0    0    0  0.0  train  
3    0    0    1    0    0    0    0    0  0.0  train  
4    0    0    1    0    0    0    0    0  0.0  train

In [22]:
bd_all.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16  V17  \
0  33   1   3   2   8   0   5   1   3    7    0    2    1    2    6    1    2   
1  37   1   2   2   8   1   4   1   4    6    2    2    0    4    5    0    5   
2  37   1   2   2   8   0   4   2   4    3    2    4    4    4    2    0    5   
3   9   1   3   3   3   2   3   2   4    5    2    2    2    3    4    3    4   
4  40   1   4   2  10   1   4   1   4    7    1    2    2    4    4    5    4   

   V18  V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  V31  V32  \
0    7    1    0    1    2    5    2    1    1    2    6    1    1    8    8   
1    4    0    0    0    5    0    4    0    2    3    5    0    2    7    7   
2    4    0    0    0    7    0    2    0    5    0    4    0    7    2    7   
3    2    4    0    0    3    1    2    3    2    1    4    0    5    4    9   
4    0    0    5    4    0    0    0    9    0    0    0    0    4    5    6   

   V33  V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  V45  V46  V47  \
0    0    1    8    1    0    4    5    0    0    4    3    0    0    0    6   
1    1    2    6    3    2    0    5    2    0    5    4    2    0    0    0   
2    0    2    9    0    4    5    0    0    0    3    4    2    0    0    6   
3    0    0    7    2    1    5    3    0    0    4    4    0    0    0    6   
4    2    1    5    4    0    0    9    0    0    6    3    0    0    0    0   

   V48  V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  V59  V60  V61  V62  \
0    0    0    0    0    0    0    0    0    0    0    0    5    0    0    0   
1    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    6    0    0    0   

   V63  V64  V65  V66  V67  V68  V69  V70  V71  V72  V73  V74  V75  V76  V77  \
0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   
1    0    0    2    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    1    0    0    1    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

   V78  V79  V80  V81  V82  V83  V84  V85  V86   data  
0    0    0    1    0    0    0    0    0  0.0  train  
1    0    0    1    0    0    0    0    0  0.0  train  
2    0    0    1    0    0    0    0    0  0.0  train  
3    0    0    1    0    0    0    0    0  0.0  train  
4    0    0    1    0    0    0    0    0  0.0  train

In [23]:
bd_all.tail()

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16  \
3995  33   1   2   4   8   0   7   2   0    5    2    2    2    6    2    0   
3996  24   1   2   3   5   1   5   1   3    4    2    4    4    4    2    2   
3997  36   1   2   3   8   1   5   1   3    7    0    2    2    5    3    2   
3998  33   1   3   3   8   1   4   2   3    7    1    2    2    3    4    1   
3999   8   1   2   3   2   4   3   0   3    5    2    2    0    6    3    8   

      V17  V18  V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  \
3995    3    6    5    0    0    1    0    4    2    0    2    4    2    4   
3996    4    4    2    0    0    3    3    3    1    1    2    5    1    7   
3997    3    4    2    0    0    3    4    2    1    1    3    5    0    7   
3998    3    5    1    1    1    2    3    3    2    2    2    4    1    4   
3999    0    1    8    0    0    0    0    1    4    0    5    1    0    2   

      V31  V32  V33  V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  \
3995    5    4    4    2    3    6    3    6    0    0    0    2    3    2   
3996    2    6    0    3    7    2    3    3    2    2    0    4    2    0   
3997    2    6    1    2    6    3    2    5    3    0    0    4    3    0   
3998    5    6    2    2    7    2    1    4    4    1    0    4    3    0   
3999    7    9    0    0    2    7    0    0    7    2    0    7    8    2   

      V45  V46  V47  V48  V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  \
3995    0    0    6    0    0    0    0    0    0    0    0    0    0    0   
3996    0    0    6    0    0    0    0    0    0    0    6    0    0    0   
3997    0    0    6    0    0    0    0    0    0    0    0    0    0    0   
3998    0    0    6    0    0    0    0    0    0    0    0    0    0    0   
3999    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

      V59  V60  V61  V62  V63  V64  V65  V66  V67  V68  V69  V70  V71  V72  \
3995    3    0    0    0    0    0    1    0    0    1    0    0    0    0   
3996    4    0    0    0    0    0    0    0    0    1    0    0    0    0   
3997    3    0    0    0    1    0    0    0    0    1    0    0    0    0   
3998    0    0    0    0    0    0    0    0    0    1    0    0    0    0   
3999    4    0    0    0    0    0    1    0    0    0    0    0    0    0   

      V73  V74  V75  V76  V77  V78  V79  V80  V81  V82  V83  V84  V85  V86  \
3995    0    0    0    0    0    0    0    1    0    0    0    0    0  NaN   
3996    0    0    0    1    0    0    0    1    0    0    0    0    0  NaN   
3997    0    0    0    0    0    0    0    1    0    0    0    1    0  NaN   
3998    0    0    0    0    0    0    0    0    0    0    0    0    0  NaN   
3999    0    0    0    0    0    0    0    1    0    0    0    0    0  NaN   

      data  
3995  test  
3996  test  
3997  test  
3998  test  
3999  test

In [24]:
bd_all.shape

(9822, 87)

In [25]:
bd_all.dtypes

V1        int64
V2        int64
V3        int64
V4        int64
V5        int64
V6        int64
V7        int64
V8        int64
V9        int64
V10       int64
V11       int64
V12       int64
V13       int64
V14       int64
V15       int64
V16       int64
V17       int64
V18       int64
V19       int64
V20       int64
V21       int64
V22       int64
V23       int64
V24       int64
V25       int64
V26       int64
V27       int64
V28       int64
V29       int64
V30       int64
V31       int64
V32       int64
V33       int64
V34       int64
V35       int64
V36       int64
V37       int64
V38       int64
V39       int64
V40       int64
V41       int64
V42       int64
V43       int64
V44       int64
V45       int64
V46       int64
V47       int64
V48       int64
V49       int64
V50       int64
V51       int64
V52       int64
V53       int64
V54       int64
V55       int64
V56       int64
V57       int64
V58       int64
V59       int64
V60       int64
V61       int64
V62       int64
V63     

In [26]:
bd_all.describe()

V1           V2           V3           V4           V5  \
count  9822.000000  9822.000000  9822.000000  9822.000000  9822.000000   
mean     24.253207     1.108735     2.677561     2.996437     5.779067   
std      12.918058     0.412101     0.780701     0.804660     2.874148   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%      10.000000     1.000000     2.000000     2.000000     3.000000   
50%      30.000000     1.000000     3.000000     3.000000     7.000000   
75%      35.000000     1.000000     3.000000     3.000000     8.000000   
max      41.000000    10.000000     6.000000     6.000000    10.000000   

                V6           V7           V8           V9          V10  \
count  9822.000000  9822.000000  9822.000000  9822.000000  9822.000000   
mean      0.700672     4.637650     1.050092     3.262981     6.188964   
std       1.015107     1.721212     1.011156     1.606287     1.896070   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     4.000000     0.000000     2.000000     5.000000   
50%       0.000000     5.000000     1.000000     3.000000     6.000000   
75%       1.000000     6.000000     2.000000     4.000000     7.000000   
max       9.000000     9.000000     5.000000     9.000000     9.000000   

               V11          V12          V13          V14          V15  \
count  9822.000000  9822.000000  9822.000000  9822.000000  9822.000000   
mean      0.873142     2.286602     1.887294     3.237324     4.302891   
std       0.961955     1.710674     1.779238     1.609139     1.984152   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     1.000000     0.000000     2.000000     3.000000   
50%       1.000000     2.000000     2.000000     3.000000     4.000000   
75%       1.000000     3.000000     3.000000     4.000000     6.000000   
max       7.000000     9.000000     9.000000     9.000000     9.000000   

               V16          V17          V18          V19          V20  \
count  9822.000000  9822.000000  9822.000000  9822.000000  9822.000000   
mean      1.484525     3.307269     4.592038     1.898799     0.403278   
std       1.645968     1.723377     2.279839     1.814406     0.786792   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     2.000000     3.000000     0.000000     0.000000   
50%       1.000000     3.000000     5.000000     2.000000     0.000000   
75%       2.000000     4.000000     6.000000     3.000000     1.000000   
max       9.000000     9.000000     9.000000     9.000000     5.000000   

               V21          V22          V23          V24          V25  \
count  9822.000000  9822.000000  9822.000000  9822.000000  9822.000000   
mean      0.545714     2.877113     2.226532     2.291183     1.650682   
std       1.106349     1.846703     1.748025     1.684008     1.742410   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     2.000000     1.000000     1.000000     0.000000   
50%       0.000000     3.000000     2.000000     2.000000     1.000000   
75%       1.000000     4.000000     3.000000     3.000000     2.000000   
max       9.000000     9.000000     9.000000     9.000000     9.000000   

               V26          V27          V28          V29          V30  \
count  9822.000000  9822.000000  9822.000000  9822.000000  9822.000000   
mean      1.595093     2.204744     3.742211     1.068214     4.187742   
std       1.321487     1.534163     1.944900     1.298229     3.093127   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       1.000000     1.000000     2.000000     0.000000     2.000000   
50%       2.000000     2.000000     4.000000     1.000000     4.000000   
75%       2.000000     3.000000     5.000000     2.000000     7.000000   
max       9.000000     9.000000     9.000000     9.000000     9.000000   

              

In [27]:
list(zip(bd_all.columns,bd_all.dtypes,bd_all.nunique())) # gives the type and
#the number of unique values present for each column

[('V1', dtype('int64'), 40),
 ('V2', dtype('int64'), 9),
 ('V3', dtype('int64'), 6),
 ('V4', dtype('int64'), 6),
 ('V5', dtype('int64'), 10),
 ('V6', dtype('int64'), 10),
 ('V7', dtype('int64'), 10),
 ('V8', dtype('int64'), 6),
 ('V9', dtype('int64'), 10),
 ('V10', dtype('int64'), 10),
 ('V11', dtype('int64'), 8),
 ('V12', dtype('int64'), 10),
 ('V13', dtype('int64'), 10),
 ('V14', dtype('int64'), 10),
 ('V15', dtype('int64'), 10),
 ('V16', dtype('int64'), 10),
 ('V17', dtype('int64'), 10),
 ('V18', dtype('int64'), 10),
 ('V19', dtype('int64'), 10),
 ('V20', dtype('int64'), 6),
 ('V21', dtype('int64'), 10),
 ('V22', dtype('int64'), 10),
 ('V23', dtype('int64'), 10),
 ('V24', dtype('int64'), 10),
 ('V25', dtype('int64'), 10),
 ('V26', dtype('int64'), 10),
 ('V27', dtype('int64'), 10),
 ('V28', dtype('int64'), 10),
 ('V29', dtype('int64'), 10),
 ('V30', dtype('int64'), 10),
 ('V31', dtype('int64'), 10),
 ('V32', dtype('int64'), 10),
 ('V33', dtype('int64'), 9),
 ('V34', dtype('int64'), 1

In [28]:
print(bd_all['V1'].unique()) # gives the unique values in the column
print(bd_all['V1'].nunique()) # gives the number of unique values
bd_all['V1'].value_counts() # gives counts of each unique value in the column

[33 37  9 40 23 39 11 10 41 38 22 13 31 34 24  8  7  3 36 25 20 12 35 30
 29 32  1 26  2  4 16  5 21  6 18 27 28 17 15 19]
40


33    1401
38     569
8      546
39     542
9      460
3      433
23     376
36     373
35     362
41     355
34     325
24     324
31     318
13     302
11     286
10     271
32     234
37     233
1      218
6      209
12     194
30     190
22     169
2      148
29     139
40     137
25     129
4       90
26      79
27      77
7       72
5       70
20      42
28      41
21      29
18      27
16      25
17      13
15       7
19       7
Name: V1, dtype: int64

In [29]:
cat_vars=bd_all.select_dtypes(['object']).columns

In [30]:
cat_vars

Index(['data'], dtype='object')

In [31]:
bd_all.shape

(9822, 87)

In [32]:
bd_all.dtypes

V1        int64
V2        int64
V3        int64
V4        int64
V5        int64
V6        int64
V7        int64
V8        int64
V9        int64
V10       int64
V11       int64
V12       int64
V13       int64
V14       int64
V15       int64
V16       int64
V17       int64
V18       int64
V19       int64
V20       int64
V21       int64
V22       int64
V23       int64
V24       int64
V25       int64
V26       int64
V27       int64
V28       int64
V29       int64
V30       int64
V31       int64
V32       int64
V33       int64
V34       int64
V35       int64
V36       int64
V37       int64
V38       int64
V39       int64
V40       int64
V41       int64
V42       int64
V43       int64
V44       int64
V45       int64
V46       int64
V47       int64
V48       int64
V49       int64
V50       int64
V51       int64
V52       int64
V53       int64
V54       int64
V55       int64
V56       int64
V57       int64
V58       int64
V59       int64
V60       int64
V61       int64
V62       int64
V63     

In [33]:
bd_all['V86'].value_counts()

0.0    5474
1.0     348
Name: V86, dtype: int64

In [34]:
list(zip(bd_all.columns,bd_all.dtypes,bd_all.nunique())) # gives the type and
#the number of unique values present for each column

[('V1', dtype('int64'), 40),
 ('V2', dtype('int64'), 9),
 ('V3', dtype('int64'), 6),
 ('V4', dtype('int64'), 6),
 ('V5', dtype('int64'), 10),
 ('V6', dtype('int64'), 10),
 ('V7', dtype('int64'), 10),
 ('V8', dtype('int64'), 6),
 ('V9', dtype('int64'), 10),
 ('V10', dtype('int64'), 10),
 ('V11', dtype('int64'), 8),
 ('V12', dtype('int64'), 10),
 ('V13', dtype('int64'), 10),
 ('V14', dtype('int64'), 10),
 ('V15', dtype('int64'), 10),
 ('V16', dtype('int64'), 10),
 ('V17', dtype('int64'), 10),
 ('V18', dtype('int64'), 10),
 ('V19', dtype('int64'), 10),
 ('V20', dtype('int64'), 6),
 ('V21', dtype('int64'), 10),
 ('V22', dtype('int64'), 10),
 ('V23', dtype('int64'), 10),
 ('V24', dtype('int64'), 10),
 ('V25', dtype('int64'), 10),
 ('V26', dtype('int64'), 10),
 ('V27', dtype('int64'), 10),
 ('V28', dtype('int64'), 10),
 ('V29', dtype('int64'), 10),
 ('V30', dtype('int64'), 10),
 ('V31', dtype('int64'), 10),
 ('V32', dtype('int64'), 10),
 ('V33', dtype('int64'), 9),
 ('V34', dtype('int64'), 1

In [35]:
print(bd_all['V1'].unique()) # gives the unique values in the column
print(bd_all['V1'].nunique()) # gives the number of unique values
bd_all['V1'].value_counts() # gives counts of each unique value in the column

[33 37  9 40 23 39 11 10 41 38 22 13 31 34 24  8  7  3 36 25 20 12 35 30
 29 32  1 26  2  4 16  5 21  6 18 27 28 17 15 19]
40


33    1401
38     569
8      546
39     542
9      460
3      433
23     376
36     373
35     362
41     355
34     325
24     324
31     318
13     302
11     286
10     271
32     234
37     233
1      218
6      209
12     194
30     190
22     169
2      148
29     139
40     137
25     129
4       90
26      79
27      77
7       72
5       70
20      42
28      41
21      29
18      27
16      25
17      13
15       7
19       7
Name: V1, dtype: int64

In [36]:
bd_all['V1'].count()

9822

In [37]:
bd_all["V1"].value_counts()

33    1401
38     569
8      546
39     542
9      460
3      433
23     376
36     373
35     362
41     355
34     325
24     324
31     318
13     302
11     286
10     271
32     234
37     233
1      218
6      209
12     194
30     190
22     169
2      148
29     139
40     137
25     129
4       90
26      79
27      77
7       72
5       70
20      42
28      41
21      29
18      27
16      25
17      13
15       7
19       7
Name: V1, dtype: int64

In [38]:
bd_all["V1"]=bd_all["V1"].astype("str")

In [39]:
bd_all["V1_33"]=np.where(bd_all["V1"]=="33",1,0)
bd_all["V1_38"]=np.where(bd_all["V1"]=="38",1,0)
bd_all["V1_8"]=np.where(bd_all["V1"]=="8",1,0)
bd_all["V1_39"]=np.where(bd_all["V1"]=="39",1,0)
bd_all["V1_9"]=np.where(bd_all["V1"]=="9",1,0)
bd_all["V1_3"]=np.where(bd_all["V1"]=="3",1,0)
bd_all["V1_23"]=np.where(bd_all["V1"]=="23",1,0)
bd_all["V1_36"]=np.where(bd_all["V1"]=="36",1,0)
bd_all["V1_35"]=np.where(bd_all["V1"]=="35",1,0)
bd_all["V1_41"]=np.where(bd_all["V1"]=="41",1,0)
bd_all["V1_34"]=np.where(bd_all["V1"]=="34",1,0)
bd_all["V1_24"]=np.where(bd_all["V1"]=="24",1,0)
bd_all["V1_31"]=np.where(bd_all["V1"]=="31",1,0)
bd_all["V1_13"]=np.where(bd_all["V1"]=="13",1,0)
bd_all["V1_11"]=np.where(bd_all["V1"]=="11",1,0)
bd_all["V1_10"]=np.where(bd_all["V1"]=="10",1,0)
bd_all["V1_32"]=np.where(bd_all["V1"]=="32",1,0)
bd_all["V1_37"]=np.where(bd_all["V1"]=="37",1,0)
bd_all["V1_1"]=np.where(bd_all["V1"]=="1",1,0)
bd_all["V1_6"]=np.where(bd_all["V1"]=="6",1,0)
bd_all["V1_12"]=np.where(bd_all["V1"]=="12",1,0)
bd_all["V1_30"]=np.where(bd_all["V1"]=="30",1,0)
bd_all["V1_22"]=np.where(bd_all["V1"]=="22",1,0)
bd_all["V1_2"]=np.where(bd_all["V1"]=="2",1,0)
bd_all["V1_29"]=np.where(bd_all["V1"]=="29",1,0)
bd_all["V1_40"]=np.where(bd_all["V1"]=="40",1,0)
bd_all["V1_25"]=np.where(bd_all["V1"]=="25",1,0)
bd_all["V1_4"]=np.where(bd_all["V1"]=="4",1,0)
bd_all["V1_26"]=np.where(bd_all["V1"]=="26",1,0)
bd_all["V1_27"]=np.where(bd_all["V1"]=="27",1,0)
bd_all["V1_7"]=np.where(bd_all["V1"]=="7",1,0)
bd_all["V1_5"]=np.where(bd_all["V1"]=="5",1,0)
bd_all["V1_20"]=np.where(bd_all["V1"]=="20",1,0)
bd_all["V1_28"]=np.where(bd_all["V1"]=="28",1,0)
bd_all["V1_21"]=np.where(bd_all["V1"]=="21",1,0)
bd_all["V1_18"]=np.where(bd_all["V1"]=="18",1,0)
bd_all["V1_16"]=np.where(bd_all["V1"]=="16",1,0)
bd_all["V1_17"]=np.where(bd_all["V1"]=="17",1,0)
bd_all["V1_15"]=np.where(bd_all["V1"]=="15",1,0)
bd_all["V1_19"]=np.where(bd_all["V1"]=="19",1,0)

bd_all=bd_all.drop(["V1"],1)

In [40]:
bd_all.shape

(9822, 126)

In [41]:
bd_all=bd_all.drop(["V1_19"],1)

In [42]:
bd_all.shape

(9822, 125)

In [43]:
bd_all.head()

V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16  V17  \
0   1   3   2   8   0   5   1   3    7    0    2    1    2    6    1    2   
1   1   2   2   8   1   4   1   4    6    2    2    0    4    5    0    5   
2   1   2   2   8   0   4   2   4    3    2    4    4    4    2    0    5   
3   1   3   3   3   2   3   2   4    5    2    2    2    3    4    3    4   
4   1   4   2  10   1   4   1   4    7    1    2    2    4    4    5    4   

   V18  V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  V31  V32  \
0    7    1    0    1    2    5    2    1    1    2    6    1    1    8    8   
1    4    0    0    0    5    0    4    0    2    3    5    0    2    7    7   
2    4    0    0    0    7    0    2    0    5    0    4    0    7    2    7   
3    2    4    0    0    3    1    2    3    2    1    4    0    5    4    9   
4    0    0    5    4    0    0    0    9    0    0    0    0    4    5    6   

   V33  V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  V45  V46  V47  \
0    0    1    8    1    0    4    5    0    0    4    3    0    0    0    6   
1    1    2    6    3    2    0    5    2    0    5    4    2    0    0    0   
2    0    2    9    0    4    5    0    0    0    3    4    2    0    0    6   
3    0    0    7    2    1    5    3    0    0    4    4    0    0    0    6   
4    2    1    5    4    0    0    9    0    0    6    3    0    0    0    0   

   V48  V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  V59  V60  V61  V62  \
0    0    0    0    0    0    0    0    0    0    0    0    5    0    0    0   
1    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    2    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    6    0    0    0   

   V63  V64  V65  V66  V67  V68  V69  V70  V71  V72  V73  V74  V75  V76  V77  \
0    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   
1    0    0    2    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    1    0    0    1    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

   V78  V79  V80  V81  V82  V83  V84  V85  V86   data  V1_33  V1_38  V1_8  \
0    0    0    1    0    0    0    0    0  0.0  train      1      0     0   
1    0    0    1    0    0    0    0    0  0.0  train      0      0     0   
2    0    0    1    0    0    0    0    0  0.0  train      0      0     0   
3    0    0    1    0    0    0    0    0  0.0  train      0      0     0   
4    0    0    1    0    0    0    0    0  0.0  train      0      0     0   

   V1_39  V1_9  V1_3  V1_23  V1_36  V1_35  V1_41  V1_34  V1_24  V1_31  V1_13  \
0      0     0     0      0      0      0      0      0      0      0      0   
1      0     0     0      0      0      0      0      0      0      0      0   
2      0     0     0      0      0      0      0      0      0      0      0   
3      0     1     0      0      0      0      0      0      0      0      0   
4      0     0     0      0      0      0      0      0      0      0      0   

   V1_11  V1_10  V1_32  V1_37  V1_1  V1_6  V1_12  V1_30  V1_22  V1_2  V1_29  \
0      0      0      0      0     0     0      0      0      0     0      0   
1      0      0      0      1     0     0      0      0      0     0      0   
2      0      0      0      1     0     0      0      0      0     0      0   
3      0      0      0      0     0     0      0      0      0     0      0   
4      0      0      0      0     0     0      0      0      0     0      0   

   V1_40  V1_25  V1_4  V1_26  V1_27  V1_7  V1_5  V1_20  V1_28  V1_21  V1_18  \
0      0      0     0      0      0     0     0      0      0      0      0   
1      0      0     0      0      0    

In [44]:
bd_all.dtypes

V2         int64
V3         int64
V4         int64
V5         int64
V6         int64
V7         int64
V8         int64
V9         int64
V10        int64
V11        int64
V12        int64
V13        int64
V14        int64
V15        int64
V16        int64
V17        int64
V18        int64
V19        int64
V20        int64
V21        int64
V22        int64
V23        int64
V24        int64
V25        int64
V26        int64
V27        int64
V28        int64
V29        int64
V30        int64
V31        int64
V32        int64
V33        int64
V34        int64
V35        int64
V36        int64
V37        int64
V38        int64
V39        int64
V40        int64
V41        int64
V42        int64
V43        int64
V44        int64
V45        int64
V46        int64
V47        int64
V48        int64
V49        int64
V50        int64
V51        int64
V52        int64
V53        int64
V54        int64
V55        int64
V56        int64
V57        int64
V58        int64
V59        int64
V60        int

In [45]:
print(bd_all['V4'].unique()) # gives the unique values in the column
print(bd_all['V4'].nunique()) # gives the number of unique values
bd_all['V4'].value_counts() # gives counts of each unique value in the column

[2 3 1 4 5 6]
6


3    5154
2    2409
4    1777
5     329
1     104
6      49
Name: V4, dtype: int64

In [46]:
bd_all["V4"]=bd_all["V4"].astype("str")

In [47]:
bd_all["V4_3"]=np.where(bd_all["V4"]=="3",1,0)
bd_all["V4_2"]=np.where(bd_all["V4"]=="2",1,0)
bd_all["V4_4"]=np.where(bd_all["V4"]=="4",1,0)
bd_all["V4_5"]=np.where(bd_all["V4"]=="5",1,0)
bd_all["V4_1"]=np.where(bd_all["V4"]=="1",1,0)
bd_all["V4_6"]=np.where(bd_all["V4"]=="6",1,0)

In [48]:
bd_all.shape

(9822, 131)

In [49]:
bd_all=bd_all.drop(["V4_6"],1)

In [50]:
bd_all=bd_all.drop(["V4"],1)

In [51]:
bd_all.shape

(9822, 129)

In [52]:
bd_all.head()

V2  V3  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16  V17  V18  \
0   1   3   8   0   5   1   3    7    0    2    1    2    6    1    2    7   
1   1   2   8   1   4   1   4    6    2    2    0    4    5    0    5    4   
2   1   2   8   0   4   2   4    3    2    4    4    4    2    0    5    4   
3   1   3   3   2   3   2   4    5    2    2    2    3    4    3    4    2   
4   1   4  10   1   4   1   4    7    1    2    2    4    4    5    4    0   

   V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  V31  V32  V33  \
0    1    0    1    2    5    2    1    1    2    6    1    1    8    8    0   
1    0    0    0    5    0    4    0    2    3    5    0    2    7    7    1   
2    0    0    0    7    0    2    0    5    0    4    0    7    2    7    0   
3    4    0    0    3    1    2    3    2    1    4    0    5    4    9    0   
4    0    5    4    0    0    0    9    0    0    0    0    4    5    6    2   

   V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  V45  V46  V47  V48  \
0    1    8    1    0    4    5    0    0    4    3    0    0    0    6    0   
1    2    6    3    2    0    5    2    0    5    4    2    0    0    0    0   
2    2    9    0    4    5    0    0    0    3    4    2    0    0    6    0   
3    0    7    2    1    5    3    0    0    4    4    0    0    0    6    0   
4    1    5    4    0    0    9    0    0    6    3    0    0    0    0    0   

   V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  V59  V60  V61  V62  V63  \
0    0    0    0    0    0    0    0    0    0    0    5    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0    2    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    2    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    2    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    6    0    0    0    0   

   V64  V65  V66  V67  V68  V69  V70  V71  V72  V73  V74  V75  V76  V77  V78  \
0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0   
1    0    2    0    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    1    0    0    1    0    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

   V79  V80  V81  V82  V83  V84  V85  V86   data  V1_33  V1_38  V1_8  V1_39  \
0    0    1    0    0    0    0    0  0.0  train      1      0     0      0   
1    0    1    0    0    0    0    0  0.0  train      0      0     0      0   
2    0    1    0    0    0    0    0  0.0  train      0      0     0      0   
3    0    1    0    0    0    0    0  0.0  train      0      0     0      0   
4    0    1    0    0    0    0    0  0.0  train      0      0     0      0   

   V1_9  V1_3  V1_23  V1_36  V1_35  V1_41  V1_34  V1_24  V1_31  V1_13  V1_11  \
0     0     0      0      0      0      0      0      0      0      0      0   
1     0     0      0      0      0      0      0      0      0      0      0   
2     0     0      0      0      0      0      0      0      0      0      0   
3     1     0      0      0      0      0      0      0      0      0      0   
4     0     0      0      0      0      0      0      0      0      0      0   

   V1_10  V1_32  V1_37  V1_1  V1_6  V1_12  V1_30  V1_22  V1_2  V1_29  V1_40  \
0      0      0      0     0     0      0      0      0     0      0      0   
1      0      0      1     0     0      0      0      0     0      0      0   
2      0      0      1     0     0      0      0      0     0      0      0   
3      0      0      0     0     0      0      0      0     0      0      0   
4      0      0      0     0     0      0      0      0     0      0      1   

   V1_25  V1_4  V1_26  V1_27  V1_7  V1_5  V1_20  V1_28  V1_21  V1_18  V1_16  \
0      0     0      0      0     0     0      0      0      0      0      0   
1      0     0      0

In [53]:
print(bd_all['V5'].unique()) # gives the unique values in the column
print(bd_all['V5'].nunique()) # gives the number of unique values
bd_all['V5'].value_counts() # gives counts of each unique value in the column

[ 8  3 10  5  9  7  2  1  6  4]
10


8     2694
3     1513
9     1111
1      959
5      940
7      881
2      827
10     492
6      326
4       79
Name: V5, dtype: int64

In [54]:
bd_all["V5"]=bd_all["V5"].astype("str")

In [55]:
bd_all["V5_8"]=np.where(bd_all["V5"]=="8",1,0)
bd_all["V5_3"]=np.where(bd_all["V5"]=="3",1,0)
bd_all["V5_9"]=np.where(bd_all["V5"]=="9",1,0)
bd_all["V5_1"]=np.where(bd_all["V5"]=="1",1,0)
bd_all["V5_5"]=np.where(bd_all["V5"]=="5",1,0)
bd_all["V5_7"]=np.where(bd_all["V5"]=="7",1,0)
bd_all["V5_2"]=np.where(bd_all["V5"]=="2",1,0)
bd_all["V5_10"]=np.where(bd_all["V5"]=="10",1,0)
bd_all["V5_6"]=np.where(bd_all["V5"]=="6",1,0)
bd_all["V5_4"]=np.where(bd_all["V5"]=="4",1,0)

In [56]:
bd_all.shape

(9822, 139)

In [57]:
bd_all=bd_all.drop(["V5_4"],1)

In [58]:
bd_all=bd_all.drop(["V5"],1)

In [59]:
bd_all.shape

(9822, 137)

In [60]:
print(bd_all['V6'].unique()) # gives the unique values in the column
print(bd_all['V6'].nunique()) # gives the number of unique values
bd_all['V6'].value_counts() # gives counts of each unique value in the column

[0 1 2 3 4 6 5 9 7 8]
10


0    5420
1    2744
2    1213
3     243
4     123
5      30
6      25
7      11
9      10
8       3
Name: V6, dtype: int64

In [61]:
bd_all["V6"]=bd_all["V6"].astype("str")

In [62]:
bd_all["V6_0"]=np.where(bd_all["V6"]=="0",1,0)
bd_all["V6_1"]=np.where(bd_all["V6"]=="1",1,0)
bd_all["V6_2"]=np.where(bd_all["V6"]=="2",1,0)
bd_all["V6_3"]=np.where(bd_all["V6"]=="3",1,0)
bd_all["V6_4"]=np.where(bd_all["V6"]=="4",1,0)
bd_all["V6_5"]=np.where(bd_all["V6"]=="5",1,0)
bd_all["V6_6"]=np.where(bd_all["V6"]=="6",1,0)
bd_all["V6_7"]=np.where(bd_all["V6"]=="7",1,0)
bd_all["V6_9"]=np.where(bd_all["V6"]=="9",1,0)
bd_all["V6_8"]=np.where(bd_all["V6"]=="8",1,0)

In [63]:
bd_all.shape

(9822, 147)

In [64]:
bd_all=bd_all.drop(["V6_8"],1)

In [65]:
bd_all=bd_all.drop(["V6"],1)

In [66]:
bd_all.shape

(9822, 145)

In [67]:
print(bd_all['V44'].unique()) # gives the unique values in the column
print(bd_all['V44'].nunique()) # gives the number of unique values
bd_all['V44'].value_counts() # gives counts of each unique value in the column

[0 2 1 3]
4


0    5903
2    3562
1     341
3      16
Name: V44, dtype: int64

In [68]:
bd_all['V86'].value_counts()

0.0    5474
1.0     348
Name: V86, dtype: int64

In [69]:
bd_train['V86'].value_counts()

0    5474
1     348
Name: V86, dtype: int64

In [70]:
bd_train.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85', 'V86', 'data'],
      dtype='object')

In [71]:
bd_all['V2'].value_counts()

1     8915
2      821
3       64
7        8
4        4
6        3
5        3
10       2
8        2
Name: V2, dtype: int64

In [72]:
bd_all['V3'].value_counts()

3    4513
2    3616
4    1132
1     452
5     106
6       3
Name: V3, dtype: int64

In [73]:
for col in ['V2','V3','V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85']:
    
    temp=pd.get_dummies(bd_all[col],prefix=col,drop_first=True)
    bd_all=pd.concat([temp,bd_all],1)
    bd_all.drop([col],1,inplace=True)
    

In [74]:
bd_all["V3_3"]

0       1
1       0
2       0
3       1
4       0
       ..
3995    0
3996    0
3997    0
3998    1
3999    0
Name: V3_3, Length: 9822, dtype: uint8

In [75]:
bd_all.dtypes

V85_1    uint8
V85_2    uint8
V84_1    uint8
V84_2    uint8
V83_1    uint8
         ...  
V6_4     int32
V6_5     int32
V6_6     int32
V6_7     int32
V6_9     int32
Length: 567, dtype: object

In [76]:
bd_all.shape

(9822, 567)

In [77]:
bd_train=bd_all[bd_all['data']=='train'] # Select only those rows where the data column has the value 'train'

In [78]:
del bd_train['data'] # Remove the data column from bd_train data frame

In [79]:
bd_test=bd_all[bd_all['data']=='test'] # Select only those rows where the data column has the value 'test'

In [80]:
bd_test.drop(['V86','data'],axis=1,inplace=True) # Remove the data and Interest.Rate column from bd_test data frame

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [81]:
bd_all.shape

(9822, 567)

In [82]:
bd_train.shape

(5822, 566)

In [83]:
bd_test.shape

(4000, 565)

In [84]:
del bd_all

In [85]:
bd_train.isnull().sum()

V85_1    0
V85_2    0
V84_1    0
V84_2    0
V83_1    0
        ..
V6_4     0
V6_5     0
V6_6     0
V6_7     0
V6_9     0
Length: 566, dtype: int64

In [86]:
bd_train.dropna(axis=0,inplace=True)

In [87]:
bd_test.isnull().sum()

V85_1    0
V85_2    0
V84_1    0
V84_2    0
V83_1    0
        ..
V6_4     0
V6_5     0
V6_6     0
V6_7     0
V6_9     0
Length: 565, dtype: int64

In [88]:
bd_test.dropna(axis=0,inplace=True)

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
bd_train1, bd_test1 = train_test_split(bd_train, test_size = 0.2,random_state=2)

In [91]:
x_train1=bd_train1.drop(['V86'],1)
y_train1=bd_train1['V86']

In [92]:
x_test1=bd_test1.drop(['V86'],1)
y_test1=bd_test1['V86']

In [ ]:
# x_train1.reset_index(drop=True,inplace=True)
# y_train1.reset_index(drop=True,inplace=True)

In [93]:
x_train1.shape

(4657, 565)

In [94]:
y_train1.shape

(4657,)

In [95]:
x_test1.shape

(1165, 565)

In [96]:
y_test1.shape

(1165,)

In [97]:
from sklearn.linear_model import LogisticRegression

In [98]:
from sklearn.metrics import roc_auc_score

In [99]:
model = LogisticRegression(fit_intercept=True)

In [104]:
params = {'class_weight':['balanced'],
        'n_jobs':[-1],
'penalty':['l1','l2'],
'C':np.linspace(1,1000,10)}

In [105]:
params

{'class_weight': ['balanced'],
 'n_jobs': [-1],
 'penalty': ['l1', 'l2'],
 'C': array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.])}

In [106]:
grid_search = GridSearchCV(model,param_grid=params,cv=5,scoring="roc_auc")

In [107]:
grid_search.fit(x_train1 , y_train1)

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: Future

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: Future

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: Future

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.]),
                         'class_weight': ['balanced'], 'n_jobs': [-1],
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc

In [108]:
logr = grid_search.best_estimator_

In [109]:
logr.fit(x_train1,y_train1)

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=-1, penalty='l1',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [110]:
roc_auc_score(y_test1 , logr.predict(x_test1))

0.6813761467889908

In [111]:
prob_score=pd.Series(list(zip(*logr.predict_proba(x_train1)))[1])

In [112]:
prob_score

0       0.396957
1       0.267338
2       0.113860
3       0.045411
4       0.159665
          ...   
4652    0.050598
4653    0.238406
4654    0.041890
4655    0.303063
4656    0.159888
Length: 4657, dtype: float64

In [113]:
cutoffs=np.linspace(0,1,100)

In [114]:
KS_cut=[]
for cutoff in cutoffs:
    predicted=pd.Series([0]*len(y_train1))
    predicted[prob_score>cutoff]=1
    df=pd.DataFrame(list(zip(y_train1,predicted)),columns=["real","predicted"])
    TP=len(df[(df["real"]==1) &(df["predicted"]==1) ])
    FP=len(df[(df["real"]==0) &(df["predicted"]==1) ])
    TN=len(df[(df["real"]==0) &(df["predicted"]==0) ])
    FN=len(df[(df["real"]==1) &(df["predicted"]==0) ])
    P=TP+FN
    N=TN+FP
    KS=(TP/P)-(FP/N)
    KS_cut.append(KS)

cutoff_data=pd.DataFrame(list(zip(cutoffs,KS_cut)),columns=["cutoff","KS"])

KS_cutoff=cutoff_data[cutoff_data["KS"]==cutoff_data["KS"].max()]["cutoff"]

In [115]:
# Performance on test data
prob_score_test=pd.Series(list(zip(*logr.predict_proba(x_test1)))[1])

predicted_test=pd.Series([0]*len(y_test1))
predicted_test[prob_score_test>float(KS_cutoff)]=1

df_test=pd.DataFrame(list(zip(y_test1,predicted_test)),columns=["real","predicted"])

k=pd.crosstab(df_test['real'],df_test["predicted"])
print('confusion matrix :\n \n ',k)
TN=k.iloc[0,0]
TP=k.iloc[1,1]
FP=k.iloc[0,1]
FN=k.iloc[1,0]
P=TP+FN
N=TN+FP

confusion matrix :
 
  predicted    0    1
real               
0.0        857  233
1.0         32   43


In [116]:
# Accuracy of test
(TP+TN)/(P+N)

0.7725321888412017

In [117]:
# Sensitivity on test
TP/P

0.5733333333333334

In [118]:
#Specificity on test
TN/N

0.7862385321100918

In [119]:
cutoffs=np.linspace(0.010,0.99,100)
def Fbeta_perf(beta,cutoffs,y_train1,prob_score):
    FB_cut=[]
    for cutoff in cutoffs:
        predicted=pd.Series([0]*len(y_train1))
        predicted[prob_score>cutoff]=1
        df=pd.DataFrame(list(zip(y_train1,predicted)),columns=["real","predicted"])

        TP=len(df[(df["real"]==1) &(df["predicted"]==1) ])
        FP=len(df[(df["real"]==0) &(df["predicted"]==1) ])
        FN=len(df[(df["real"]==1) &(df["predicted"]==0) ])
        P=TP+FN
        
        
        Precision=TP/(TP+FP)
        Recall=TP/P
        FB=(1+beta**2)*Precision*Recall/((beta**2)*Precision+Recall)
        FB_cut.append(FB)

    cutoff_data=pd.DataFrame(list(zip(cutoffs,FB_cut)),columns=["cutoff","FB"])

    FB_cutoff=cutoff_data[cutoff_data["FB"]==cutoff_data["FB"].max()]["cutoff"]

    prob_score_test=pd.Series(list(zip(*logr.predict_proba(x_test1)))[1])

    predicted_test=pd.Series([0]*len(y_test1))
    predicted_test[prob_score_test>float(FB_cutoff)]=1

    df_test=pd.DataFrame(list(zip(y_test1,predicted_test)),columns=["real","predicted"])

    k=pd.crosstab(df_test['real'],df_test["predicted"])
    
#print('confusion matrix :\n \n ',k)
    TN=k.iloc[0,0]
    TP=k.iloc[1,1]
    FP=k.iloc[0,1]
    FN=k.iloc[1,0]
    P=TP+FN
    N=TN+FP
    print('For beta :',beta)
    print('Accuracy is :',(TP+TN)/(P+N))
    print('Sensitivity is :',(TP/P))
    print('Specificity is :',(TN/N))
    print('\n \n \n')

In [120]:
Fbeta_perf(0.5,cutoffs,y_train1,prob_score)
Fbeta_perf(1,cutoffs,y_train1,prob_score)
Fbeta_perf(3,cutoffs,y_train1,prob_score)
Fbeta_perf(2,cutoffs,y_train1,prob_score)

For beta : 0.5
Accuracy is : 0.8763948497854077
Sensitivity is : 0.3333333333333333
Specificity is : 0.9137614678899083

 
 

For beta : 1
Accuracy is : 0.8446351931330472
Sensitivity is : 0.37333333333333335
Specificity is : 0.8770642201834863

 
 

For beta : 3
Accuracy is : 0.7725321888412017
Sensitivity is : 0.5733333333333334
Specificity is : 0.7862385321100918

 
 

For beta : 2
Accuracy is : 0.7931330472103004
Sensitivity is : 0.56
Specificity is : 0.8091743119266055

 
 



In [141]:
cutoffs

array([0.01      , 0.01989899, 0.02979798, 0.03969697, 0.04959596,
       0.05949495, 0.06939394, 0.07929293, 0.08919192, 0.09909091,
       0.1089899 , 0.11888889, 0.12878788, 0.13868687, 0.14858586,
       0.15848485, 0.16838384, 0.17828283, 0.18818182, 0.19808081,
       0.2079798 , 0.21787879, 0.22777778, 0.23767677, 0.24757576,
       0.25747475, 0.26737374, 0.27727273, 0.28717172, 0.29707071,
       0.3069697 , 0.31686869, 0.32676768, 0.33666667, 0.34656566,
       0.35646465, 0.36636364, 0.37626263, 0.38616162, 0.39606061,
       0.4059596 , 0.41585859, 0.42575758, 0.43565657, 0.44555556,
       0.45545455, 0.46535354, 0.47525253, 0.48515152, 0.49505051,
       0.50494949, 0.51484848, 0.52474747, 0.53464646, 0.54454545,
       0.55444444, 0.56434343, 0.57424242, 0.58414141, 0.5940404 ,
       0.60393939, 0.61383838, 0.62373737, 0.63363636, 0.64353535,
       0.65343434, 0.66333333, 0.67323232, 0.68313131, 0.6930303 ,
       0.70292929, 0.71282828, 0.72272727, 0.73262626, 0.74252

In [142]:
train_score=logr.predict_proba(x_train1)[:,1] # the predicted response variablevalues
real=y_train1 # the actual response variable values
print(logr.classes_) # In order to find the probability of which column is for outcome 1 and which for outcome 0

[0. 1.]


In [143]:
from sklearn.metrics import fbeta_score

In [144]:
KS_all=[]
fbeta05_all=[]
fbeta5_all=[]
fbeta2_all=[]
fbeta3_all=[]
for cutoff in cutoffs:

    predicted=(train_score>cutoff).astype(int)

    TP=((predicted==1) & (real==1)).sum()
    TN=((predicted==0) & (real==0)).sum()
    FP=((predicted==1) & (real==0)).sum()
    FN=((predicted==0) & (real==1)).sum()

    P=TP+FN
    N=TN+FP

    KS=(TP/P)-(FP/N)

    KS_all.append(KS)

    precision = TP/(TP+FP)
    recall = TP/P

    fbeta05 = ((1 + 0.05**2)*precision*recall)/(0.05**2*precision + recall)
    fbeta5 = ((1 + 5**2)*precision*recall)/(5**2*precision + recall)
    fbeta2 = ((1 + 2**2)*precision*recall)/(2**2*precision + recall)
    fbeta3 = ((1 + 3**2)*precision*recall)/(3**2*precision + recall)

    fbeta05_all.append(fbeta05)
    fbeta5_all.append(fbeta5)
    fbeta2_all.append(fbeta2)
    fbeta3_all.append(fbeta3)

In [145]:
list(zip(cutoffs,fbeta2_all))

[(0.01, 0.27310924369747897),
 (0.0198989898989899, 0.29235382308845576),
 (0.029797979797979796, 0.3072248480756246),
 (0.039696969696969696, 0.3204977694294435),
 (0.049595959595959596, 0.33163265306122447),
 (0.059494949494949496, 0.34227683049147445),
 (0.06939393939393938, 0.3521671826625387),
 (0.07929292929292929, 0.3599683544303797),
 (0.08919191919191918, 0.3681229773462783),
 (0.09909090909090908, 0.37541254125412543),
 (0.10898989898989898, 0.38256726457399104),
 (0.11888888888888888, 0.39156626506024095),
 (0.12878787878787878, 0.39819136522753784),
 (0.1386868686868687, 0.4052850356294537),
 (0.1485858585858586, 0.411144578313253),
 (0.15848484848484848, 0.4187116564417177),
 (0.16838383838383839, 0.42483660130718953),
 (0.1782828282828283, 0.42992125984251967),
 (0.18818181818181817, 0.43735982057033007),
 (0.19808080808080808, 0.4446254071661238),
 (0.207979797979798, 0.4512396694214876),
 (0.21787878787878787, 0.45851528384279483),
 (0.22777777777777777, 0.4641278476708

In [146]:
mycutoff=cutoffs[fbeta2_all==max(fbeta2_all)][0]

In [147]:
mycutoff 

0.5247474747474747

In [148]:
test_score=logr.predict_proba(bd_test)[:,1]

In [149]:
test_score

array([0.03062389, 0.36667554, 0.70862707, ..., 0.42172466, 0.61058824,
       0.05623112])

In [151]:
test_classes = test_score > mycutoff

In [152]:
test_classes

array([False, False,  True, ..., False,  True, False])

In [153]:
test_classes = (test_score > mycutoff).astype(int)

In [154]:
test_classes

array([0, 0, 1, ..., 0, 1, 0])

In [155]:
dataframe = pd.DataFrame(test_classes, columns=['V86'])

In [156]:
dataframe

V86
0       0
1       0
2       1
3       1
4       0
...   ...
3995    0
3996    0
3997    0
3998    1
3999    0

[4000 rows x 1 columns]

In [157]:
dataframe.to_csv("Nitesh_Bhosle_project2(carvan)_p2_Logistic_Regression.csv",index=False)

In [ ]:
## f beta score by using grid search

In [158]:
y_train_2_pred = grid_search.predict(x_test1).astype(int)

In [159]:
fbeta_score(y_test1 , y_train_2_pred , average="weighted" , beta=2)

0.8012928496441383

In [160]:
grid_search.classes_

array([0., 1.])

In [ ]:
## f beta score by using logr.predict

In [162]:
y_train_2_pred11 = logr.predict(x_test1).astype(int)

In [163]:
fbeta_score(y_test1 , y_train_2_pred11 , average="weighted" , beta=2)

0.8012928496441383

In [164]:
logr.classes_

array([0., 1.])

In [ ]:
## test prediction using grid search

In [207]:
test_prediction = grid_search.predict_proba(bd_test)

In [212]:
test_prediction

array([[0.96937611, 0.03062389],
       [0.63332446, 0.36667554],
       [0.29137293, 0.70862707],
       ...,
       [0.57827534, 0.42172466],
       [0.38941176, 0.61058824],
       [0.94376888, 0.05623112]])

In [ ]:
## test prediction using logr.predict

In [194]:
test_prediction11 = logr.predict_proba(bd_test)

In [195]:
test_prediction11

array([[0.96937611, 0.03062389],
       [0.63332446, 0.36667554],
       [0.29137293, 0.70862707],
       ...,
       [0.57827534, 0.42172466],
       [0.38941176, 0.61058824],
       [0.94376888, 0.05623112]])

In [ ]:
## hard classess (grid search)

In [209]:
test_hard_classes = (test_prediction[:,1]>0.8012928496441383).astype(int)

In [210]:
test_hard_classes

array([0, 0, 0, ..., 0, 0, 0])

In [188]:
df = pd.DataFrame(test_hard_classes, columns=['V86'])
df.to_csv("Submission_Project2_Logistic_Regression_Submission_002.csv",index=False)

In [189]:
df

V86
0       0
1       0
2       0
3       1
4       0
...   ...
3995    0
3996    0
3997    0
3998    0
3999    0

[4000 rows x 1 columns]

In [ ]:
## hard class (logr.predict)

In [196]:
test_hard_classes11 = (test_prediction11[:,1]>0.8012928496441383).astype(int)

In [197]:
test_hard_classes11

array([0, 0, 0, ..., 0, 0, 0])

In [198]:
df11 = pd.DataFrame(test_hard_classes, columns=['V86'])
df.to_csv("Submission_Project2_Logistic_Regression(logr.predict)_Submission_002.csv",index=False)

In [199]:
df11

V86
0       0
1       0
2       0
3       1
4       0
...   ...
3995    0
3996    0
3997    0
3998    0
3999    0

[4000 rows x 1 columns]

In [67]:
logr = LogisticRegression(penalty="l1",class_weight="balanced",random_state=2)

In [68]:
logr.fit(x_train1,y_train1)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l1', random_state=2,
          solver='warn', tol=0.0001, verbose=0, warm_start=False)

In [69]:
# score model performance on the test data
roc_auc_score(y_test1,logr.predict(x_test1))

0.6813761467889908

In [70]:
prob_score=pd.Series(list(zip(*logr.predict_proba(x_train1)))[1])

In [71]:
cutoffs=np.linspace(0,1,100)

In [72]:
KS_cut=[]
for cutoff in cutoffs:
    predicted=pd.Series([0]*len(y_train1))
    predicted[prob_score>cutoff]=1
    df=pd.DataFrame(list(zip(y_train1,predicted)),columns=["real","predicted"])
    TP=len(df[(df["real"]==1) &(df["predicted"]==1) ])
    FP=len(df[(df["real"]==0) &(df["predicted"]==1) ])
    TN=len(df[(df["real"]==0) &(df["predicted"]==0) ])
    FN=len(df[(df["real"]==1) &(df["predicted"]==0) ])
    P=TP+FN
    N=TN+FP
    KS=(TP/P)-(FP/N)
    KS_cut.append(KS)

cutoff_data=pd.DataFrame(list(zip(cutoffs,KS_cut)),columns=["cutoff","KS"])

KS_cutoff=cutoff_data[cutoff_data["KS"]==cutoff_data["KS"].max()]["cutoff"]

In [73]:
# Performance on test data
prob_score_test=pd.Series(list(zip(*logr.predict_proba(x_test1)))[1])

predicted_test=pd.Series([0]*len(y_test1))
predicted_test[prob_score_test>float(KS_cutoff)]=1

df_test=pd.DataFrame(list(zip(y_test1,predicted_test)),columns=["real","predicted"])

k=pd.crosstab(df_test['real'],df_test["predicted"])
print('confusion matrix :\n \n ',k)
TN=k.iloc[0,0]
TP=k.iloc[1,1]
FP=k.iloc[0,1]
FN=k.iloc[1,0]
P=TP+FN
N=TN+FP

confusion matrix :
 
  predicted    0    1
real               
0.0        857  233
1.0         32   43


In [74]:
# Accuracy of test
(TP+TN)/(P+N)

0.7725321888412017

In [75]:
# Sensitivity on test
TP/P

0.5733333333333334

In [76]:
#Specificity on test
TN/N

0.7862385321100918

In [77]:
cutoffs=np.linspace(0.010,0.99,100)
def Fbeta_perf(beta,cutoffs,y_train1,prob_score):
    FB_cut=[]
    for cutoff in cutoffs:
        predicted=pd.Series([0]*len(y_train1))
        predicted[prob_score>cutoff]=1
        df=pd.DataFrame(list(zip(y_train1,predicted)),columns=["real","predicted"])

        TP=len(df[(df["real"]==1) &(df["predicted"]==1) ])
        FP=len(df[(df["real"]==0) &(df["predicted"]==1) ])
        FN=len(df[(df["real"]==1) &(df["predicted"]==0) ])
        P=TP+FN
        
        
        Precision=TP/(TP+FP)
        Recall=TP/P
        FB=(1+beta**2)*Precision*Recall/((beta**2)*Precision+Recall)
        FB_cut.append(FB)

    cutoff_data=pd.DataFrame(list(zip(cutoffs,FB_cut)),columns=["cutoff","FB"])

    FB_cutoff=cutoff_data[cutoff_data["FB"]==cutoff_data["FB"].max()]["cutoff"]

    prob_score_test=pd.Series(list(zip(*logr.predict_proba(x_test1)))[1])

    predicted_test=pd.Series([0]*len(y_test1))
    predicted_test[prob_score_test>float(FB_cutoff)]=1

    df_test=pd.DataFrame(list(zip(y_test1,predicted_test)),columns=["real","predicted"])

    k=pd.crosstab(df_test['real'],df_test["predicted"])
    
#print('confusion matrix :\n \n ',k)
    TN=k.iloc[0,0]
    TP=k.iloc[1,1]
    FP=k.iloc[0,1]
    FN=k.iloc[1,0]
    P=TP+FN
    N=TN+FP
    print('For beta :',beta)
    print('Accuracy is :',(TP+TN)/(P+N))
    print('Sensitivity is :',(TP/P))
    print('Specificity is :',(TN/N))
    print('\n \n \n')

In [78]:
Fbeta_perf(0.5,cutoffs,y_train1,prob_score)
Fbeta_perf(1,cutoffs,y_train1,prob_score)
Fbeta_perf(2,cutoffs,y_train1,prob_score)

For beta : 0.5
Accuracy is : 0.8763948497854077
Sensitivity is : 0.3333333333333333
Specificity is : 0.9137614678899083

 
 

For beta : 1
Accuracy is : 0.8446351931330472
Sensitivity is : 0.37333333333333335
Specificity is : 0.8770642201834863

 
 

For beta : 2
Accuracy is : 0.7931330472103004
Sensitivity is : 0.56
Specificity is : 0.8091743119266055

 
 



In [79]:
cutoffs

array([0.01      , 0.01989899, 0.02979798, 0.03969697, 0.04959596,
       0.05949495, 0.06939394, 0.07929293, 0.08919192, 0.09909091,
       0.1089899 , 0.11888889, 0.12878788, 0.13868687, 0.14858586,
       0.15848485, 0.16838384, 0.17828283, 0.18818182, 0.19808081,
       0.2079798 , 0.21787879, 0.22777778, 0.23767677, 0.24757576,
       0.25747475, 0.26737374, 0.27727273, 0.28717172, 0.29707071,
       0.3069697 , 0.31686869, 0.32676768, 0.33666667, 0.34656566,
       0.35646465, 0.36636364, 0.37626263, 0.38616162, 0.39606061,
       0.4059596 , 0.41585859, 0.42575758, 0.43565657, 0.44555556,
       0.45545455, 0.46535354, 0.47525253, 0.48515152, 0.49505051,
       0.50494949, 0.51484848, 0.52474747, 0.53464646, 0.54454545,
       0.55444444, 0.56434343, 0.57424242, 0.58414141, 0.5940404 ,
       0.60393939, 0.61383838, 0.62373737, 0.63363636, 0.64353535,
       0.65343434, 0.66333333, 0.67323232, 0.68313131, 0.6930303 ,
       0.70292929, 0.71282828, 0.72272727, 0.73262626, 0.74252

In [80]:
train_score=logr.predict_proba(x_train1)[:,1] # the predicted response variablevalues
real=y_train1 # the actual response variable values
print(logr.classes_) # In order to find the probability of which column is for outcome 1 and which for outcome 0

[0. 1.]


In [81]:
from sklearn.metrics import fbeta_score

In [82]:
KS_all=[]
fbeta05_all=[]
fbeta5_all=[]
fbeta2_all=[]

for cutoff in cutoffs:

    predicted=(train_score>cutoff).astype(int)

    TP=((predicted==1) & (real==1)).sum()
    TN=((predicted==0) & (real==0)).sum()
    FP=((predicted==1) & (real==0)).sum()
    FN=((predicted==0) & (real==1)).sum()

    P=TP+FN
    N=TN+FP

    KS=(TP/P)-(FP/N)

    KS_all.append(KS)

    precision = TP/(TP+FP)
    recall = TP/P

    fbeta05 = ((1 + 0.05**2)*precision*recall)/(0.05**2*precision + recall)
    fbeta5 = ((1 + 5**2)*precision*recall)/(5**2*precision + recall)
    fbeta2 = ((1 + 2**2)*precision*recall)/(2**2*precision + recall)

    fbeta05_all.append(fbeta05)
    fbeta5_all.append(fbeta5)
    fbeta2_all.append(fbeta2)

In [83]:
list(zip(cutoffs,fbeta2_all))

[(0.01, 0.27310924369747897),
 (0.0198989898989899, 0.29235382308845576),
 (0.029797979797979796, 0.3072248480756246),
 (0.039696969696969696, 0.3204977694294435),
 (0.049595959595959596, 0.33163265306122447),
 (0.059494949494949496, 0.34227683049147445),
 (0.06939393939393938, 0.35225806451612907),
 (0.07929292929292929, 0.3599683544303797),
 (0.08919191919191918, 0.3681229773462783),
 (0.09909090909090908, 0.37541254125412543),
 (0.10898989898989898, 0.38256726457399104),
 (0.11888888888888888, 0.39156626506024095),
 (0.12878787878787878, 0.39819136522753784),
 (0.1386868686868687, 0.4052850356294537),
 (0.1485858585858586, 0.411144578313253),
 (0.15848484848484848, 0.4187116564417177),
 (0.16838383838383839, 0.42483660130718953),
 (0.1782828282828283, 0.42992125984251967),
 (0.18818181818181817, 0.43735982057033007),
 (0.19808080808080808, 0.4446254071661238),
 (0.207979797979798, 0.4512396694214876),
 (0.21787878787878787, 0.45851528384279483),
 (0.22777777777777777, 0.464127847670

In [84]:
mycutoff=cutoffs[fbeta2_all==max(fbeta2_all)][0]
mycutoff 

0.5247474747474747

In [85]:
test_score=logr.predict_proba(bd_test)[:,1]
test_score

array([0.03062646, 0.36667271, 0.70862848, ..., 0.42171424, 0.61058602,
       0.05623096])

In [86]:
test_classes=(test_score>mycutoff).astype(int)

In [87]:
mycutoff

0.5247474747474747

In [88]:
df = pd.DataFrame(test_classes, columns=['V86'])
df.to_csv("Submission_Project2_Logistic_Regression_Submission_002.csv",index=False)