In [58]:
import pandas as pd
import numpy as np
import re
import datetime
from dateutil.relativedelta import relativedelta
from datetime import date
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
%matplotlib inline

In [59]:
file = r"C:\Users\Mr. Jarvis\Desktop\python project\project 2\carvan_train.csv"

In [60]:
file

'C:\\Users\\Mr. Jarvis\\Desktop\\python project\\project 2\\carvan_train.csv'

In [61]:
carvan_train = pd.read_csv(file)

In [62]:
carvan_train

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  ...  V77  V78  V79  V80  V81  \
0     33   1   3   2   8   0   5   1   3    7  ...    0    0    0    1    0   
1     37   1   2   2   8   1   4   1   4    6  ...    0    0    0    1    0   
2     37   1   2   2   8   0   4   2   4    3  ...    0    0    0    1    0   
3      9   1   3   3   3   2   3   2   4    5  ...    0    0    0    1    0   
4     40   1   4   2  10   1   4   1   4    7  ...    0    0    0    1    0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
5817  36   1   1   2   8   0   6   1   2    1  ...    0    0    0    1    0   
5818  35   1   4   4   8   1   4   1   4    6  ...    0    0    0    1    0   
5819  33   1   3   4   8   0   6   0   3    5  ...    0    0    0    1    0   
5820  34   1   3   2   8   0   7   0   2    7  ...    0    0    0    0    0   
5821  33   1   3   3   8   0   6   1   2    7  ...    0    0    0    0    0   

      V82  V83  V84  V85  V86  
0       0    0    0    0    0  
1       0    0    0    0    0  
2       0    0    0    0    0  
3       0    0    0    0    0  
4       0    0    0    0    0  
...   ...  ...  ...  ...  ...  
5817    0    0    0    0    0  
5818    0    0    0    0    0  
5819    0    0    0    0    1  
5820    0    0    0    0    0  
5821    0    0    0    0    0  

[5822 rows x 86 columns]

In [63]:
file = r"C:\Users\Mr. Jarvis\Desktop\python project\project 2\carvan_test.csv"

In [64]:
file

'C:\\Users\\Mr. Jarvis\\Desktop\\python project\\project 2\\carvan_test.csv'

In [65]:
carvan_test = pd.read_csv(file)

In [66]:
carvan_test

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  ...  V76  V77  V78  V79  V80  \
0     33   1   4   2   8   0   6   0   3    5  ...    0    0    0    0    1   
1      6   1   3   2   2   0   5   0   4    5  ...    2    0    0    0    1   
2     39   1   3   3   9   1   4   2   3    5  ...    1    0    0    0    1   
3      9   1   2   3   3   2   3   2   4    5  ...    0    0    0    0    1   
4     31   1   2   4   7   0   2   0   7    9  ...    0    0    0    0    1   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
3995  33   1   2   4   8   0   7   2   0    5  ...    0    0    0    0    1   
3996  24   1   2   3   5   1   5   1   3    4  ...    1    0    0    0    1   
3997  36   1   2   3   8   1   5   1   3    7  ...    0    0    0    0    1   
3998  33   1   3   3   8   1   4   2   3    7  ...    0    0    0    0    0   
3999   8   1   2   3   2   4   3   0   3    5  ...    0    0    0    0    1   

      V81  V82  V83  V84  V85  
0       0    0    0    0    0  
1       0    0    0    0    0  
2       0    0    0    0    0  
3       0    0    0    0    0  
4       0    0    0    0    0  
...   ...  ...  ...  ...  ...  
3995    0    0    0    0    0  
3996    0    0    0    0    0  
3997    0    0    0    1    0  
3998    0    0    0    0    0  
3999    0    0    0    0    0  

[4000 rows x 85 columns]

In [67]:
carvan_train.shape

(5822, 86)

In [68]:
carvan_test.shape

(4000, 85)

In [69]:
carvan_train.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85', 'V86'],
      dtype='object')

In [70]:
carvan_test.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85'],
      dtype='object')

In [71]:
carvan_train.dtypes

V1     int64
V2     int64
V3     int64
V4     int64
V5     int64
       ...  
V82    int64
V83    int64
V84    int64
V85    int64
V86    int64
Length: 86, dtype: object

In [72]:
carvan_train.select_dtypes("object")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[5822 rows x 0 columns]

In [73]:
carvan_test.dtypes

V1     int64
V2     int64
V3     int64
V4     int64
V5     int64
       ...  
V81    int64
V82    int64
V83    int64
V84    int64
V85    int64
Length: 85, dtype: object

In [74]:
carvan_test.select_dtypes("object")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[4000 rows x 0 columns]

In [75]:
carvan_train.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
      ..
V82    0
V83    0
V84    0
V85    0
V86    0
Length: 86, dtype: int64

In [76]:
carvan_test.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
      ..
V81    0
V82    0
V83    0
V84    0
V85    0
Length: 85, dtype: int64

In [77]:
carvan_test['V86']=np.nan

In [78]:
carvan_train['data'] = 'train'

In [79]:
carvan_test['data'] = 'test'

In [80]:
carvan_train.shape

(5822, 87)

In [81]:
carvan_test.shape

(4000, 87)

In [82]:
carvan_test = carvan_test[carvan_train.columns]

In [83]:
carvan_test.shape

(4000, 87)

In [84]:
carvan_full = pd.concat([carvan_train , carvan_test] , axis=0)

In [85]:
carvan_full.shape

(9822, 87)

In [86]:
carvan_full

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  ...  V78  V79  V80  V81  V82  \
0     33   1   3   2   8   0   5   1   3    7  ...    0    0    1    0    0   
1     37   1   2   2   8   1   4   1   4    6  ...    0    0    1    0    0   
2     37   1   2   2   8   0   4   2   4    3  ...    0    0    1    0    0   
3      9   1   3   3   3   2   3   2   4    5  ...    0    0    1    0    0   
4     40   1   4   2  10   1   4   1   4    7  ...    0    0    1    0    0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
3995  33   1   2   4   8   0   7   2   0    5  ...    0    0    1    0    0   
3996  24   1   2   3   5   1   5   1   3    4  ...    0    0    1    0    0   
3997  36   1   2   3   8   1   5   1   3    7  ...    0    0    1    0    0   
3998  33   1   3   3   8   1   4   2   3    7  ...    0    0    0    0    0   
3999   8   1   2   3   2   4   3   0   3    5  ...    0    0    1    0    0   

      V83  V84  V85  V86   data  
0       0    0    0  0.0  train  
1       0    0    0  0.0  train  
2       0    0    0  0.0  train  
3       0    0    0  0.0  train  
4       0    0    0  0.0  train  
...   ...  ...  ...  ...    ...  
3995    0    0    0  NaN   test  
3996    0    0    0  NaN   test  
3997    0    1    0  NaN   test  
3998    0    0    0  NaN   test  
3999    0    0    0  NaN   test  

[9822 rows x 87 columns]

In [87]:
carvan_full.dtypes

V1        int64
V2        int64
V3        int64
V4        int64
V5        int64
         ...   
V83       int64
V84       int64
V85       int64
V86     float64
data     object
Length: 87, dtype: object

In [88]:
carvan_full.isnull().sum()

V1         0
V2         0
V3         0
V4         0
V5         0
        ... 
V83        0
V84        0
V85        0
V86     4000
data       0
Length: 87, dtype: int64

In [89]:
carvan_train = carvan_full[carvan_full['data']=='train']
del carvan_train['data'] 

In [90]:
carvan_test = carvan_full[carvan_full['data']=='test']
carvan_test.drop(['V86','data'] , axis=1 , inplace=True) 

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [102]:
carvan_train.shape

(5822, 86)

In [103]:
carvan_test.shape

(4000, 85)

In [104]:
carvan_full.shape

(9822, 87)

In [105]:
train1, train2 = train_test_split(carvan_train , test_size = 0.25,random_state=2)

In [106]:
train1.shape

(4366, 86)

In [107]:
train2.shape

(1456, 86)

In [108]:
x_train1 = train1.drop(["V86"] , 1)

y_train1 = train1["V86"]

In [109]:
x_train1.shape

(4366, 85)

In [110]:
y_train1.shape

(4366,)

In [111]:
x_train2 = train2.drop(["V86"] ,1)

y_train2 = train2["V86"]

In [112]:
x_train2.shape

(1456, 85)

In [113]:
y_train2.shape

(1456,)

In [114]:
x_train1.reset_index(drop=True,inplace=True)
y_train1.reset_index(drop=True,inplace=True)

In [115]:
model = LogisticRegression()

In [116]:
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [117]:
params={'class_weight':['balanced'],
        'n_jobs':[-1],
'penalty':['l1','l2'],
'C':np.linspace(1,1000,10)}

In [118]:
params

{'class_weight': ['balanced'],
 'n_jobs': [-1],
 'penalty': ['l1', 'l2'],
 'C': array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.])}

In [119]:
?GridSearchCV

In [133]:
grid_search=GridSearchCV(model,param_grid=params,cv=5,scoring="roc_auc")

In [134]:
grid_search

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.]),
                         'class_weight': ['balanced'], 'n_jobs': [-1],
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc

In [135]:
from sklearn.metrics import fbeta_score

In [136]:
grid_search.fit(x_train1,y_train1)

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be chan

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be chan

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be chan

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.]),
                         'class_weight': ['balanced'], 'n_jobs': [-1],
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc

In [137]:
logr = grid_search.best_estimator_

In [138]:
logr

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=-1, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [139]:
logr.fit(x_train1,y_train1)

C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Jarvis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:1544: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(effective_n_jobs(self.n_jobs)))


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=-1, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [148]:
y_train_2_pred = grid_search.predict(x_train2).astype(int)

In [156]:
y_train_2_pred

array([1, 0, 1, ..., 0, 0, 0])

In [151]:
y_train_2_pred.shape

(1456,)

In [150]:
fbeta_score(y_train2 , y_train_2_pred , average="weighted" , beta=2)

0.7309705312686163

In [153]:
y_train_1_pred = grid_search.predict(x_train1).astype(int)

In [154]:
y_train_1_pred

array([0, 1, 1, ..., 1, 0, 0])

In [155]:
y_train_1_pred.shape

(4366,)

In [157]:
fbeta_score(y_train1 , y_train_1_pred , average="weighted" , beta=2)

0.7332041066015279

In [164]:
test_prediction = grid_search.predict(carvan_test).astype(int)

In [165]:
test_prediction

array([0, 1, 0, ..., 1, 1, 1])

In [166]:
test_prediction.shape

(4000,)

In [167]:
pd.DataFrame(test_prediction).to_csv("Nitesh_Bhosle_p2_part2_carvan.csv",index=False)

In [168]:
cutoffs=np.linspace(0.01,0.99,99)

cutoffs

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [172]:
train_score_cutoff = logr.predict_proba(x_train1)[:,1]

In [173]:
train_score_cutoff

array([0.10213091, 0.79578786, 0.71974128, ..., 0.53735716, 0.13782131,
       0.21241288])

In [174]:
train1_score

array([0.10213091, 0.79578786, 0.71974128, ..., 0.53735716, 0.13782131,
       0.21241288])

In [177]:
real=y_train1.astype(int)

In [178]:
real

0       0
1       1
2       0
3       0
4       0
       ..
4361    0
4362    0
4363    0
4364    0
4365    0
Name: V86, Length: 4366, dtype: int32

In [180]:
logr.classes_.astype(int)

array([0, 1])

In [193]:
train_score_cutoff > 0.5

array([False,  True,  True, ...,  True, False, False])

In [194]:
train1_score > 0.5

array([False,  True,  True, ...,  True, False, False])

In [195]:
KS_all=[]

for cutoff in cutoffs:
    
    predicted=(train_score_cutoff>cutoff).astype(int)

    TP=((predicted==1) & (real==1)).sum()
    TN=((predicted==0) & (real==0)).sum()
    FP=((predicted==1) & (real==0)).sum()
    FN=((predicted==0) & (real==1)).sum()
    
    P=TP+FN
    N=TN+FP
      
    KS=(TP/P)-(FP/N)
    
    
    KS_all.append(KS)

In [196]:
mycutoff=cutoffs[KS_all==max(KS_all)][0]

In [197]:
mycutoff

0.55

In [198]:
logr.intercept_

array([0.50761686])

In [202]:
test_score = logr.predict_proba(carvan_test)[:,1]

In [203]:
test_score

array([0.18451596, 0.82676506, 0.48065851, ..., 0.71424042, 0.50010958,
       0.67884601])

In [204]:
test_score.shape

(4000,)

In [205]:
test_classes = (test_score>mycutoff).astype(int)

In [206]:
test_classes

array([0, 1, 0, ..., 1, 0, 1])

In [208]:
pd.DataFrame(test_classes).to_csv("Nitesh_Bhosle_p2_part2_cutoff_value.csv",index=False)